import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rekkei Acade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <head>
          <link rel="shortcut icon" href="https://learn.rikkeiacademy.com/favicon.ico.png" type="image/x-icon" />
        </head>
      </body>
    </html>
  );
}
